name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        # GitHub secret token
        repo_token: "${{ secrets.TOKEN }}"
        # Git tag (for automatic releases)
        automatic_release_tag: true
        # Should this release be marked as a draft?
        draft: true
        # Should this release be marked as a pre-release?
        prerelease: true
        # Release title (for automatic releases)
        title: Milia v.1.0.${{ github.run_number }}
        # Assets to upload to the release
        files: "build/outputs/apk/debug/app-debug.apk"
      
